# Generated by Django 3.2.5 on 2023-01-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delito',
            fields=[
                ('iddelito', models.AutoField(db_column='idDelito', primary_key=True, serialize=False)),
                ('delito', models.CharField(blank=True, db_column='Delito', max_length=300, null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Delito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('idfecha', models.AutoField(db_column='idFecha', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
            ],
            options={
                'db_table': 'Fecha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geopoint',
            fields=[
                ('idgeopoint', models.AutoField(db_column='idGeoPoint', primary_key=True, serialize=False)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GeoPoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hechoscrimen',
            fields=[
                ('idhechoscrimen', models.AutoField(db_column='idHechosCrimen', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'HechosCrimen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=15, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
            ],
            options={
                'db_table': 'Persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idubicacion', models.AutoField(db_column='idUbicacion', primary_key=True, serialize=False)),
                ('alcaldia', models.CharField(blank=True, db_column='Alcaldia', max_length=35, null=True)),
                ('colonia', models.CharField(blank=True, db_column='Colonia', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Ubicacion',
                'managed': False,
            },
        ),
    ]
