# Generated by Django 3.2.5 on 2023-01-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafTendencias', '0002_auto_20230105_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fecha',
            options={'managed': False, 'ordering': ('fecha',)},
        ),
    ]
